// generate_version_info.js

import { setTimeout } from 'node:timers/promises';
import fse from 'fs-extra';

const default_output_path = "src/version_info.ts";
let output_path = default_output_path;

function get_version_info() {
  const pkg_name = process.env.npm_package_name;
  const pkg_version = process.env.npm_package_version;
  let r_str = "";
  r_str += `// ${output_path}\n`;
  r_str += `// generated by generate_version_info.js\n\n`;
  r_str += `const subg_version_short = '${pkg_version}';\n`;
  r_str += `const subg_version_long = '${pkg_name}_${pkg_version}.0_abc_123';\n`;
  r_str += `\nexport {subg_version_short, subg_version_long};\n`;
  return r_str;
}


console.log("Hello from generate_version_info.js");

//console.log(Date.now());
//const res = await setTimeout(2000, Date.now() );
//console.log(res);
//console.log(Date.now());

//console.log(process.env);
//console.log(process.env.npm_package_name);
//console.log(process.env.npm_package_version);

const f_str = get_version_info();
//console.log(f_str);
fse.outputFile(output_path, f_str);

console.log("Bye from generate_version_info.js");
